name: deutsche_lernen_a1
description: ApplicaciÃ³n para repasar el vocabulario para el nivel N5 de japones.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.0+1

environment:
  sdk: ">=2.12.0 <3.0.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  sqflite:
  path:
  image:
  path_provider:
  permission_handler:
  open_file:
  flutter_local_notifications:
  confetti:
  chips_choice:
  flutter_gif: any
  painter:
  devtools_server:
  dwds:
  flutter_html:
  cupertino_icons:
  flutter_launcher_icons:
  flutter_inappwebview: ^5.3.2
  step_progress_indicator:

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_android: "assets/launcher/nihongo2.png"
  image_path_ios: "assets/launcher/nihongo2.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/deutsch_lernen_a1.db
    - assets/background.jpg
    - assets/launcher/nihongo2.png